-- =====================================================================
-- 04 · DIMENSIONES  (esquema: dw)
-- =====================================================================
-- Cuatro decisiones que vale la pena defender:
--
-- 1. LLAVES SUSTITUTAS. Enteras, sin significado. Permiten guardar varias
--    versiones de la misma persona y hacen las uniones mas baratas.
--    Excepcion deliberada: dim_tiempo usa una llave con forma AAAAMMDD,
--    porque hace legible el hecho sin unir y ordena igual que la fecha.
--
-- 2. FILA -1 EN CADA DIMENSION. Cuando el hecho trae una llave que no
--    existe, apunta a "Desconocido" en vez de quedarse en NULL. Asi las
--    uniones siguen siendo internas y no se pierden filas del hecho.
--
-- 3. TIPO DE CAMBIO LENTO POR DIMENSION, no uno para todas:
--      dim_asesor   TIPO 2  la oficina cambia y la historia importa
--      dim_cliente  TIPO 1  el telefono cambia y solo interesa el actual
--      dim_producto TIPO 1  casi estatica
--      dim_oficina  TIPO 1  el catalogo de agencias
--
-- 4. COLUMNA _hash. Resumen de los atributos que se vigilan. Detectar un
--    cambio es comparar un valor, no quince columnas.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS dw;

-- ---------------------------------------------------------------------
-- DIM TIEMPO · estatica, no viene del origen
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS dw.dim_tiempo CASCADE;
CREATE TABLE dw.dim_tiempo (
  sk_tiempo      INT       PRIMARY KEY,     -- AAAAMMDD
  fecha          DATE      NOT NULL UNIQUE,
  anio           SMALLINT  NOT NULL,
  trimestre      SMALLINT  NOT NULL,
  mes            SMALLINT  NOT NULL,
  nombre_mes     VARCHAR(12) NOT NULL,
  dia            SMALLINT  NOT NULL,
  dia_semana     SMALLINT  NOT NULL,        -- 1 lunes .. 7 domingo
  nombre_dia     VARCHAR(12) NOT NULL,
  es_fin_semana  BOOLEAN   NOT NULL,
  anio_mes       CHAR(7)   NOT NULL         -- 2026-03
);

INSERT INTO dw.dim_tiempo
SELECT to_char(d,'YYYYMMDD')::INT,
       d::date,
       extract(year    FROM d)::smallint,
       extract(quarter FROM d)::smallint,
       extract(month   FROM d)::smallint,
       initcap(to_char(d,'TMMonth')),
       extract(day     FROM d)::smallint,
       extract(isodow  FROM d)::smallint,
       initcap(to_char(d,'TMDay')),
       extract(isodow  FROM d) >= 6,
       to_char(d,'YYYY-MM')
FROM generate_series(DATE '2025-01-01', DATE '2028-12-31', INTERVAL '1 day') d;

-- fila desconocida
INSERT INTO dw.dim_tiempo VALUES
  (-1, DATE '1900-01-01', 1900, 1, 1, 'Desconocido', 1, 1, 'Desconocido', false, '1900-01');

-- ---------------------------------------------------------------------
-- DIM ASESOR · TIPO 2 · la unica con historia
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS dw.dim_asesor CASCADE;
CREATE TABLE dw.dim_asesor (
  sk_asesor    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_asesor    VARCHAR(10) NOT NULL,            -- llave natural, se repite
  nombre       VARCHAR(120),
  region       VARCHAR(60),
  oficina      VARCHAR(60),
  puesto       VARCHAR(40),
  cargo        VARCHAR(40),
  estado       VARCHAR(20),
  desde        DATE    NOT NULL,
  hasta        DATE    NOT NULL DEFAULT DATE '9999-12-31',
  vigente      BOOLEAN NOT NULL DEFAULT true,
  _hash        TEXT,
  _cargado_en  TIMESTAMP NOT NULL DEFAULT now()
);

-- una sola version vigente por persona: esto impide el error mas comun del SCD2
CREATE UNIQUE INDEX ux_dim_asesor_vigente
  ON dw.dim_asesor (id_asesor) WHERE vigente;
-- buscar la version correcta segun la fecha del hecho
CREATE INDEX ix_dim_asesor_rango
  ON dw.dim_asesor (id_asesor, desde, hasta);

INSERT INTO dw.dim_asesor
  (sk_asesor, id_asesor, nombre, region, oficina, puesto, cargo, estado, desde, hasta, vigente)
VALUES
  (-1, 'N/D', 'Desconocido', 'Desconocido', 'Desconocido', 'N/D', 'N/D', 'N/D',
   DATE '1900-01-01', DATE '9999-12-31', true);

COMMENT ON COLUMN dw.dim_asesor.sk_asesor IS 'Llave sustituta: identifica ESTA VERSION del asesor, no a la persona';
COMMENT ON COLUMN dw.dim_asesor.id_asesor IS 'Llave natural: identifica a la persona, se repite entre versiones';
COMMENT ON COLUMN dw.dim_asesor._hash     IS 'md5 de los atributos vigilados; si cambia, nace una version nueva';

-- ---------------------------------------------------------------------
-- DIM CLIENTE · TIPO 1 · se sobrescribe
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS dw.dim_cliente CASCADE;
CREATE TABLE dw.dim_cliente (
  sk_cliente     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_lead        VARCHAR(20) NOT NULL UNIQUE,
  nombre_cliente VARCHAR(120),
  documento      VARCHAR(15),
  telefono       VARCHAR(15),
  distrito       VARCHAR(60),
  canal          VARCHAR(40),
  score_riesgo   INT,
  tramo_score    VARCHAR(20),       -- atributo derivado: agrupa el score
  prioridad      SMALLINT,
  _hash          TEXT,
  _cargado_en    TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO dw.dim_cliente
  (sk_cliente, id_lead, nombre_cliente, documento, telefono, distrito, canal,
   score_riesgo, tramo_score, prioridad)
VALUES (-1, 'N/D', 'Desconocido', NULL, NULL, 'Desconocido', 'Desconocido',
        NULL, 'Desconocido', NULL);

COMMENT ON COLUMN dw.dim_cliente.tramo_score IS
  'Agrupacion del score en bandas. Se calcula al cargar para que el negocio no tenga que definirla en cada reporte.';

-- ---------------------------------------------------------------------
-- DIM PRODUCTO · TIPO 1
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS dw.dim_producto CASCADE;
CREATE TABLE dw.dim_producto (
  sk_producto  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto     VARCHAR(60) NOT NULL UNIQUE,
  familia      VARCHAR(40),          -- derivado: Empresarial / Personal
  _cargado_en  TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO dw.dim_producto (sk_producto, producto, familia)
VALUES (-1, 'Desconocido', 'Desconocido');

-- ---------------------------------------------------------------------
-- DIM OFICINA · TIPO 1 · catalogo de agencias
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS dw.dim_oficina CASCADE;
CREATE TABLE dw.dim_oficina (
  sk_oficina   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oficina      VARCHAR(60) NOT NULL,
  region       VARCHAR(60) NOT NULL,
  _cargado_en  TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE (oficina, region)
);

INSERT INTO dw.dim_oficina (sk_oficina, oficina, region)
VALUES (-1, 'Desconocido', 'Desconocido');

-- ---------------------------------------------------------------------
-- Comprobacion
-- ---------------------------------------------------------------------
SELECT 'dim_tiempo'   AS dimension, count(*) AS filas FROM dw.dim_tiempo
UNION ALL SELECT 'dim_asesor',   count(*) FROM dw.dim_asesor
UNION ALL SELECT 'dim_cliente',  count(*) FROM dw.dim_cliente
UNION ALL SELECT 'dim_producto', count(*) FROM dw.dim_producto
UNION ALL SELECT 'dim_oficina',  count(*) FROM dw.dim_oficina
ORDER BY 1;
