-- =====================================================================
-- 06 · TABLAS DE HECHOS
-- =====================================================================
-- DOS hechos, no uno. Tienen GRANOS DISTINTOS y mezclarlos seria un error:
--
--   fact_gestion     una fila por contacto con el cliente
--   fact_desembolso  una fila por credito desembolsado
--
-- Meter el monto del desembolso dentro de fact_gestion duplicaria el
-- dinero cada vez que se cuente una gestion. Comparten dimensiones: eso
-- se llama constelacion de hechos.
--
-- DIMENSIONES DEGENERADAS: id_gestion, resultado y canal_contacto viven
-- dentro del hecho. No tienen atributos propios que justifiquen una tabla.
-- Si manana "resultado" ganara atributos (es_cierre, orden, color), se
-- convertiria en dimension.
-- =====================================================================

-- ---------------------------------------------------------------------
-- FACT GESTION · grano: una gestion
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS dw.fact_gestion CASCADE;
CREATE TABLE dw.fact_gestion (
  sk_gestion      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_gestion      BIGINT      NOT NULL UNIQUE,     -- dimension degenerada
  sk_tiempo       INT         NOT NULL REFERENCES dw.dim_tiempo (sk_tiempo),
  sk_cliente      BIGINT      NOT NULL REFERENCES dw.dim_cliente (sk_cliente),
  sk_asesor       BIGINT      NOT NULL REFERENCES dw.dim_asesor (sk_asesor),
  sk_producto     BIGINT      NOT NULL REFERENCES dw.dim_producto (sk_producto),
  sk_oficina      BIGINT      NOT NULL REFERENCES dw.dim_oficina (sk_oficina),
  resultado       VARCHAR(30) NOT NULL,            -- degenerada
  canal_contacto  VARCHAR(30),                     -- degenerada
  -- metricas
  gestiones       SMALLINT    NOT NULL DEFAULT 1,  -- contador: permite SUM en vez de COUNT
  duracion_seg    INT,
  es_desembolso   SMALLINT    NOT NULL DEFAULT 0,
  es_rechazo      SMALLINT    NOT NULL DEFAULT 0,
  es_contacto     SMALLINT    NOT NULL DEFAULT 0,
  _cargado_en     TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX ix_fg_tiempo  ON dw.fact_gestion (sk_tiempo);
CREATE INDEX ix_fg_asesor  ON dw.fact_gestion (sk_asesor);
CREATE INDEX ix_fg_oficina ON dw.fact_gestion (sk_oficina);

COMMENT ON COLUMN dw.fact_gestion.gestiones IS
  'Siempre 1. Permite SUM(gestiones) en vez de COUNT(*), que es lo que espera una herramienta de BI.';
COMMENT ON COLUMN dw.fact_gestion.sk_oficina IS
  'Oficina del asesor EN LA FECHA DE LA GESTION, tomada de la version vigente del SCD2.';

-- ---------------------------------------------------------------------
-- FACT DESEMBOLSO · grano: un desembolso
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS dw.fact_desembolso CASCADE;
CREATE TABLE dw.fact_desembolso (
  sk_desembolso   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_desembolso   BIGINT      NOT NULL UNIQUE,
  sk_tiempo       INT         NOT NULL REFERENCES dw.dim_tiempo (sk_tiempo),
  sk_cliente      BIGINT      NOT NULL REFERENCES dw.dim_cliente (sk_cliente),
  sk_asesor       BIGINT      NOT NULL REFERENCES dw.dim_asesor (sk_asesor),
  sk_producto     BIGINT      NOT NULL REFERENCES dw.dim_producto (sk_producto),
  sk_oficina      BIGINT      NOT NULL REFERENCES dw.dim_oficina (sk_oficina),
  moneda          CHAR(3)     NOT NULL,
  -- metricas
  desembolsos     SMALLINT      NOT NULL DEFAULT 1,
  monto           NUMERIC(12,2) NOT NULL,
  monto_pen       NUMERIC(12,2) NOT NULL,   -- todo llevado a soles
  monto_aprobado  NUMERIC(12,2),            -- cuanto se le habia aprobado
  plazo_meses     SMALLINT,
  tasa_anual      NUMERIC(5,2),
  _cargado_en     TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX ix_fd_tiempo ON dw.fact_desembolso (sk_tiempo);
CREATE INDEX ix_fd_asesor ON dw.fact_desembolso (sk_asesor);

COMMENT ON COLUMN dw.fact_desembolso.monto_pen IS
  'Monto convertido a soles al cargar. Evita que cada reporte invente su propio tipo de cambio.';

-- =====================================================================
-- CARGA
-- =====================================================================
-- La union con dim_asesor es la clave de todo el proyecto:
--
--   ON da.id_asesor = s.id_asesor
--  AND s.fecha BETWEEN da.desde AND da.hasta
--
-- No busca la version vigente HOY, busca la que estaba vigente EN LA
-- FECHA DEL HECHO. Por eso una gestion de enero se queda en San Isidro
-- aunque el asesor hoy este en Miraflores.
--
-- Todas las uniones son LEFT + coalesce(..., -1): si una llave no existe,
-- el hecho apunta a "Desconocido" en vez de desaparecer.
-- =====================================================================

CREATE OR REPLACE PROCEDURE dw.cargar_fact_gestion()
LANGUAGE plpgsql AS $$
DECLARE v_filas INT;
BEGIN
  MERGE INTO dw.fact_gestion f
  USING (
    SELECT g.id_gestion,
           coalesce(t.sk_tiempo,   -1) AS sk_tiempo,
           coalesce(c.sk_cliente,  -1) AS sk_cliente,
           coalesce(a.sk_asesor,   -1) AS sk_asesor,
           coalesce(p.sk_producto, -1) AS sk_producto,
           coalesce(o.sk_oficina,  -1) AS sk_oficina,
           g.resultado, g.canal_contacto, g.duracion_seg,
           CASE WHEN g.resultado = 'Desembolsado' THEN 1 ELSE 0 END AS es_desembolso,
           CASE WHEN g.resultado = 'Rechazado'    THEN 1 ELSE 0 END AS es_rechazo,
           CASE WHEN g.resultado <> 'No contesta' THEN 1 ELSE 0 END AS es_contacto
    FROM staging.stg_gestiones g
    LEFT JOIN dw.dim_tiempo  t ON t.fecha = g.registrado_en::date
    LEFT JOIN staging.stg_leads l ON l.id_lead = g.id_lead
    LEFT JOIN dw.dim_cliente c ON c.id_lead = g.id_lead
    -- la version del asesor VIGENTE EN LA FECHA DE LA GESTION
    LEFT JOIN dw.dim_asesor  a ON a.id_asesor = g.id_asesor
                              AND g.registrado_en::date BETWEEN a.desde AND a.hasta
    LEFT JOIN dw.dim_producto p ON p.producto = l.producto
    -- la oficina sale de esa misma version historica, no de la actual
    LEFT JOIN dw.dim_oficina  o ON o.oficina = a.oficina AND o.region = a.region
  ) s
  ON f.id_gestion = s.id_gestion
  WHEN MATCHED THEN UPDATE SET
       sk_tiempo = s.sk_tiempo, sk_cliente = s.sk_cliente, sk_asesor = s.sk_asesor,
       sk_producto = s.sk_producto, sk_oficina = s.sk_oficina,
       resultado = s.resultado, canal_contacto = s.canal_contacto,
       duracion_seg = s.duracion_seg, es_desembolso = s.es_desembolso,
       es_rechazo = s.es_rechazo, es_contacto = s.es_contacto, _cargado_en = now()
  WHEN NOT MATCHED THEN INSERT
       (id_gestion, sk_tiempo, sk_cliente, sk_asesor, sk_producto, sk_oficina,
        resultado, canal_contacto, duracion_seg, es_desembolso, es_rechazo, es_contacto)
  VALUES (s.id_gestion, s.sk_tiempo, s.sk_cliente, s.sk_asesor, s.sk_producto,
          s.sk_oficina, s.resultado, s.canal_contacto, s.duracion_seg,
          s.es_desembolso, s.es_rechazo, s.es_contacto);

  GET DIAGNOSTICS v_filas = ROW_COUNT;
  RAISE NOTICE 'fact_gestion: % fila(s) afectada(s)', v_filas;
END;
$$;

CREATE OR REPLACE PROCEDURE dw.cargar_fact_desembolso()
LANGUAGE plpgsql AS $$
DECLARE
  v_filas INT;
  v_tc    NUMERIC := 3.75;   -- tipo de cambio fijo; en el Proyecto 2 vendra del BCRP
BEGIN
  MERGE INTO dw.fact_desembolso f
  USING (
    SELECT d.id_desembolso,
           coalesce(t.sk_tiempo,   -1) AS sk_tiempo,
           coalesce(c.sk_cliente,  -1) AS sk_cliente,
           coalesce(a.sk_asesor,   -1) AS sk_asesor,
           coalesce(p.sk_producto, -1) AS sk_producto,
           coalesce(o.sk_oficina,  -1) AS sk_oficina,
           d.moneda, d.monto,
           CASE WHEN d.moneda = 'USD' THEN round(d.monto * v_tc, 2) ELSE d.monto END AS monto_pen,
           l.monto_aprobado, d.plazo_meses, d.tasa_anual
    FROM staging.stg_desembolsos d
    LEFT JOIN dw.dim_tiempo  t ON t.fecha = d.fecha
    LEFT JOIN staging.stg_leads l ON l.id_lead = d.id_lead
    LEFT JOIN dw.dim_cliente c ON c.id_lead = d.id_lead
    LEFT JOIN dw.dim_asesor  a ON a.id_asesor = d.id_asesor
                              AND d.fecha BETWEEN a.desde AND a.hasta
    LEFT JOIN dw.dim_producto p ON p.producto = l.producto
    LEFT JOIN dw.dim_oficina  o ON o.oficina = a.oficina AND o.region = a.region
  ) s
  ON f.id_desembolso = s.id_desembolso
  WHEN MATCHED THEN UPDATE SET
       sk_tiempo = s.sk_tiempo, sk_cliente = s.sk_cliente, sk_asesor = s.sk_asesor,
       sk_producto = s.sk_producto, sk_oficina = s.sk_oficina, moneda = s.moneda,
       monto = s.monto, monto_pen = s.monto_pen, monto_aprobado = s.monto_aprobado,
       plazo_meses = s.plazo_meses, tasa_anual = s.tasa_anual, _cargado_en = now()
  WHEN NOT MATCHED THEN INSERT
       (id_desembolso, sk_tiempo, sk_cliente, sk_asesor, sk_producto, sk_oficina,
        moneda, monto, monto_pen, monto_aprobado, plazo_meses, tasa_anual)
  VALUES (s.id_desembolso, s.sk_tiempo, s.sk_cliente, s.sk_asesor, s.sk_producto,
          s.sk_oficina, s.moneda, s.monto, s.monto_pen, s.monto_aprobado,
          s.plazo_meses, s.tasa_anual);

  GET DIAGNOSTICS v_filas = ROW_COUNT;
  RAISE NOTICE 'fact_desembolso: % fila(s) afectada(s)', v_filas;
END;
$$;

-- ---------------------------------------------------------------------
-- Orquestador del warehouse completo
-- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE dw.cargar_todo()
LANGUAGE plpgsql AS $$
BEGIN
  CALL staging.cargar_todo();
  CALL dw.cargar_dimensiones();
  CALL dw.cargar_fact_gestion();
  CALL dw.cargar_fact_desembolso();
END;
$$;

-- ---------------------------------------------------------------------
-- Vista plana para Power BI
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW dw.v_gestion AS
SELECT t.fecha, t.anio_mes, t.nombre_mes, t.es_fin_semana,
       cl.nombre_cliente, cl.tramo_score, cl.canal AS canal_origen,
       a.nombre AS asesor, a.cargo,
       o.oficina, o.region,
       pr.producto, pr.familia,
       f.resultado, f.canal_contacto,
       f.gestiones, f.duracion_seg, f.es_desembolso, f.es_rechazo, f.es_contacto
FROM dw.fact_gestion f
JOIN dw.dim_tiempo   t  ON t.sk_tiempo   = f.sk_tiempo
JOIN dw.dim_cliente  cl ON cl.sk_cliente = f.sk_cliente
JOIN dw.dim_asesor   a  ON a.sk_asesor   = f.sk_asesor
JOIN dw.dim_oficina  o  ON o.sk_oficina  = f.sk_oficina
JOIN dw.dim_producto pr ON pr.sk_producto = f.sk_producto;
